In [1]:
import numpy as np
import pandas as pd
from io import StringIO

# Day 1

In [95]:
#day 1
input = np.loadtxt("input1.txt", dtype='int')

#part 1
result = np.count_nonzero(input[1:] > input[:input.size-1])

print("Part 1: " + str(result))

#part 2
result = np.count_nonzero(input[3:] > input[:input.size-3])

print("Part 2: " + str(result))

Part 1: 1390
Part 2: 1457


# Day 2

In [96]:
#day 2
command = np.loadtxt("input2.txt", dtype='str', usecols=0)
value = np.loadtxt("input2.txt", dtype='int', usecols=1)

horizontal = 0
aim = 0
vertical = 0

for i in np.arange(command.size):
    if command[i]=="forward":
        horizontal += value[i]
        vertical += aim*value[i]
    elif command[i]=="up":
        aim -= value[i]
    else:
        aim += value[i]

print("Part 1:" + str(horizontal*aim))

print("Part 2:" + str(horizontal*vertical))

Part 1:1714680
Part 2:1963088820


# Day 3

In [97]:
# day 3
# part A
input = np.loadtxt("input3.txt", dtype='str')

length = len(input[0])

data = np.empty((input.size,length), dtype='str')

alpha = str()
beta = str()

length = len(input[0])

for index in np.arange(length):
    # reset counter for zeros and ones
    c0 = 0
    c1 = 0
    # nuller und einser zählen
    for word in np.arange(input.size):
        if input[word][index] == '0':
            c0 += 1
        else:
            c1 += 1
    # set alpha and beta bits accordingly
    if c0 > c1:
        alpha += '0'
        beta += '1'
    else:
        alpha += '1'
        beta += '0'

result = int(alpha,2) * int(beta,2)

print("Part 1: " + str(result))

Part 1: 2967914


In [98]:
#part B wrong attempt, one should discard
O2index = np.ones(input.size)
CO2index = np.ones(input.size)

done = False

for index in np.arange(length):
    for word in np.arange(input.size):
        common = alpha[index]
        if input[word][index] != common: #es geht nicht für O2
            O2index[word] = 0
        if np.count_nonzero(O2index) == 1:
            done = True
            break
    if done:
        break

done = False

for index in np.arange(length):
    for word in np.arange(input.size):
        common = beta[index]
        if input[word][index] != common: # es geht nicht für CO2
            CO2index[word] = 0
        if np.count_nonzero(CO2index) == 1:
            done = True
            break
    if done:
        break


result = int(input[np.argmax(O2index)],2) * int(input[np.argmax(CO2index)],2)
print("O2 Value: " + str(int(input[np.argmax(O2index)],2)))
print("CO2 Value: " + str(int(input[np.argmax(CO2index)],2)))
print("Part 2: " + str(result))

O2 Value: 937
CO2 Value: 3154
Part 2: 2955298


In [99]:
# part B correct
o2 = input.tolist()
co2 = input.tolist()

common = '0'

#select O2 value
for index in np.arange(length):
    c0 = 0;
    c1 = 0;
    for word in np.arange(len(o2)):
        if o2[word][index] == '0':
            c0 += 1
        else:
            c1 += 1
    if c1 >= c0:
        common = '1'
    else:
        common = '0'
    idx = 0
    while idx < len(o2) and len(o2) > 1:
        if o2[idx][index] == common:
            idx += 1
        else:
            o2.pop(idx)
    if len(o2) == 1:
        break

o2val = int(o2.pop(),2)

for index in np.arange(length):
    c0 = 0;
    c1 = 0;
    for word in np.arange(len(co2)):
        if co2[word][index] == '0':
            c0 += 1
        else:
            c1 += 1
    if c0 <= c1:
        common = '0'
    else:
        common = '1'
    idx = 0
    while idx < len(co2) and len(co2) > 1:
        if co2[idx][index] == common:
            idx += 1
        else:
            co2.pop(idx)
    if len(co2) == 1:
        break

co2val = int(co2.pop(),2)
result = co2val * o2val
print("O2 Value: " + str(o2val))
print("CO2 Value: " + str(co2val))
print("Part 2: " + str(result))

O2 Value: 1927
CO2 Value: 3654
Part 2: 7041258


# Day 4

In [100]:
def check(board):
    for i in np.arange(5):
        if np.sum(board[:,i]) == -5 or np.sum(board[i,:]) == -5:
            return True
    return False

In [101]:
def search(board,number):
    board[np.where(board==number)] = -1

In [102]:
# day 4
# numbers to get called
numbers = np.loadtxt("input4.txt", max_rows=1, delimiter=',', dtype='int')

#determine the number of boards
lines_in_input = len(open("input4.txt").readlines())
nboards = int((lines_in_input-1)/6)

#allocate memory and ready data
boards = np.array(np.zeros((nboards,5,5)))
data = np.array(pd.read_csv("input4.txt", sep='\s+', dtype='int', skiprows=2, engine='python', header=None),dtype='int')

for i in np.arange(nboards):
    boards[i] = data[5*i:5*(i+1),:]

print("Part 1: ")

for val in numbers:
    for board in boards:
        search(board,val)
        if check(board):
            print("Last number: " + str(val))
            print(board)
            board[np.where(board == -1)] = 0
            print("Result: " + str(np.sum(board)*val))
            board[:,:] = -2
            print("")

print("Part 2 is above")

Part 1: 
Last number: 80
[[41. 69. 63. 88. -1.]
 [25. 56. 23. -1. -1.]
 [ 8. 92. 59. 66. -1.]
 [48. 61. 77. 15. -1.]
 [-1. 47. 91. -1. -1.]]
Result: 74320.0

Last number: 99
[[73. -1. -1. 90. 40.]
 [16.  4. -1.  9. 29.]
 [38. -1. -1. 51. 83.]
 [86. 88. -1. 44. 32.]
 [-1. 49. -1. 43. 62.]]
Result: 82863.0

Last number: 11
[[79. -1. -1. -1. 73.]
 [38. 77. -1. 32. 53.]
 [ 2. -1. 29.  6. 89.]
 [-1. 91. 15. 47. 34.]
 [-1. -1. -1. -1. -1.]]
Result: 7315.0

Last number: 7
[[17. 65. -1. -1. -1.]
 [73. 16. 24. 67. 53.]
 [60. 93. 88. 45. 26.]
 [-1. -1. -1. -1. -1.]
 [55. -1. 49.  8. 82.]]
Result: 5747.0

Last number: 90
[[-1. -1. -1. -1. -1.]
 [-1. 96. 76. 21. 79.]
 [-1. 43. 63. 81. 56.]
 [42. 62. 23. 55. 74.]
 [45. 72. 77. -1. 47.]]
Result: 91080.0

Last number: 8
[[-1. -1. 15.  2. 49.]
 [48. 33. 23. 16.  4.]
 [-1. 41. 43. -1. 83.]
 [62. 13. 20. 63. 85.]
 [-1. -1. -1. -1. -1.]]
Result: 4800.0

Last number: 88
[[72. 69. -1. -1. -1.]
 [34. -1. -1. -1.  3.]
 [58. 18. -1. -1. 65.]
 [ 9. 47. 85. -1.

# Day 5

In [103]:
# day 5
data = np.array(pd.read_csv("input5.txt", sep=',|\s+', dtype='int', usecols=(0,1,3,4), engine='python', header=None))

ocean = np.zeros((1000,1000))

for tube in data:
    if tube[0] == tube[2] or tube[1]==tube[3]: #constant x or y coordinate
        ocean[np.linspace(tube[0],tube[2],num=np.abs(tube[0]-tube[2])+1,endpoint=True).astype(int),
              np.linspace(tube[1],tube[3],num=np.abs(tube[1]-tube[3])+1,endpoint=True).astype(int)] += 1

print("Part 1: " + str(np.count_nonzero(ocean >= 2)))

#part 2
ocean = np.zeros((1000,1000))

for tube in data:
    ocean[np.linspace(tube[0],tube[2],num=np.abs(tube[0]-tube[2])+1,endpoint=True).astype(int),
          np.linspace(tube[1],tube[3],num=np.abs(tube[1]-tube[3])+1,endpoint=True).astype(int)] += 1

print("Part 2: " + str(np.count_nonzero(ocean >= 2)))

Part 1: 5442
Part 2: 19571


In [104]:
# Graveyard: Remember remeber what linspace can do and arange can't
if tube[0] == tube[2]: #constant x coordinate
    if tube[3]<tube[1]: #lower y at endpoint
        ocean[tube[0],tube[3]:tube[1]+1] += 1
    else:
        ocean[tube[0],tube[1]:tube[3]+1] += 1
elif tube[1] == tube[3]: #constant y coordinate
    if tube[2] < tube[0]:
        ocean[tube[2]:tube[0]+1,tube[1]] += 1
    else:
        ocean[tube[0]:tube[2]+1,tube[1]] += 1
else: #diagonal line
    if tube[2] < tube[0]:
        if tube[3] < tube[1]:
            ocean[tube[2]+np.arange(tube[0]-tube[2]+1),tube[3]+np.arange(tube[0]-tube[2]+1)] += 1
        else:
            ocean[tube[2]+np.arange(tube[0]-tube[2]+1),tube[1]+np.arange(tube[0]-tube[2]+1)] += 1
    else:
        if tube[3] < tube[1]:
            ocean[tube[0]+np.arange(tube[2]-tube[0]+1),tube[3]+np.arange(tube[2]-tube[0]+1)] += 1
        else:
            ocean[tube[0]+np.arange(tube[2]-tube[0]+1),tube[1]+np.arange(tube[2]-tube[0]+1)] += 1
### Gleiches wie
ocean[np.linspace(tube[0],tube[2],num=np.abs(tube[0]-tube[2])+1,endpoint=True).astype(int),
      np.linspace(tube[1],tube[3],num=np.abs(tube[1]-tube[3])+1,endpoint=True).astype(int)] += 1

# Day 6

In [93]:
# fast solution counting fish
# day 6
# part 1
data = np.loadtxt("input6.txt", dtype='int', delimiter=",")

days = 256
fish = np.zeros(9)

for val in data:
    fish[val] += 1

for day in np.arange(days):
    newfish = np.zeros(9)
    newfish[:8] = fish[1:]
    newfish[8] = fish[0]
    newfish[6] += fish[0]
    fish = newfish
    if day == 79:
        print("Part 1: " + str(np.sum(fish)))

print("Part 2: " + str(np.sum(fish)))

Part 1: 394994.0
Part 2: 1765974267455.0


In [80]:
# slow attempt simulating all fish
# day 6
# part 1
data = np.loadtxt("input6.txt", dtype='int', delimiter=",")


#input = np.array([3])
days= 80
newfish=0

for i in np.arange(days-1):
    data -= 1

    newfish = 0
    for j in np.arange(data.size):
        if data[j] == 0:
            data[j] = 7
            newfish += 1
    data = np.append(data, 9*np.ones(newfish))

print("Part 1: " + str(data.size))

Part 1: 394994


In [10]:
def simulateNewbornFish(days):
    counter = 1
    if days < 9: #on 9th day reach maturity
        return counter
    else:
        days -= 9
        counter += simulateNewbornFish(days)
        while days >= 7:
            days -= 7
            counter += simulateNewbornFish(days)
    return counter

In [19]:
def simulateFish(days):
    counter = 0
    for i in np.arange(np.ceil(days/7)):
        counter += simulateNewbornFish(days - 7*i)
    return counter

In [91]:
# failed attempt with recursion
# day 6
# part 1
input = np.loadtxt("test.txt", dtype='int', delimiter=",")

#input = np.array([3])
counter = 0
days= 2

for i in input:
    counter += simulateFish(days-i)

print("Part 1: " + str(counter))

Part 1: 5


# Day 7

In [29]:
# day 7 part 1
data = np.loadtxt("input7.txt", dtype='int', delimiter=",")

length = np.max(data) - np.min(data)+1
result1 = np.zeros(length)
result2 = np.zeros(length)
idx = 0

for pos in np.linspace(np.min(data), np.max(data), result.size):
    result1[idx] = np.sum(np.abs(data-pos))
    result2[idx] = np.sum(np.abs(data - pos)*(np.abs(data - pos)+1)/2)
    idx += 1

print("Part 1: " + str(np.min(result1)))
print("Part 1: " + str(np.min(result2)))

Part 1: 336120.0
Part 1: 96864235.0
